### ISSUE TITLE
How do you develop this?

### ISSUE THREAD

**Issue by asesidaa** [fatal-bundy/nesys_at_home#1]
Hi, I am trying to continue development to support GC4EX, but the request to certify.php always error out with error in CertFindCertificateInStore(), which I assume is an error related to SSL. So I wonder what is your development workflow?

Currently, what I do is that I patched NesysService to connect to localhost, and I just set up a server on localhost with certificate generated using mkcert. I can access localhost using https in browser just fine. Am I missing something? 

Thank you

**Comment by fatal-bundy** [comment]
Hey asesidaa

There is a few methods I used depending on the deployment.

If all on a local machine then a self sign cert with the CA in the OS cert
store will work fine.

When this isn't possible you can do a doll injection similar to the jvs emu
by romhack.

Then there is the proxy dll if you have no way to inject a dll. Look at my
nxl2 repo for an example of this

Both the dll methods you will be looking at hijacking the API call that
says if the ssl cert should be verified or not. Ms docs should be able to
help find this.

The third option was going to be my method for a public release and have it
change the hostnames to something I controlled and could have a real cert
for.

**Comment by asesidaa** [comment]
Hi, thank you for reply!
I found out that the issue is by default, without modification, the https connections are using a certificate issued by taito themselves with the CN=Taito Arcade Machine CA. After creating a self signed CA with the same name, the issue is now solved!

**Comment by asesidaa** [comment]
Hi, currently, when I send card data to NesysService, it successfully get the data, but seems to fail at transfering data to game. 
And after searching around, this seems to be related to the "1\n1,1\n" before the actual response. So I wonder what are these mysterious 1s and newlines? Thanks!

**Comment by asesidaa** [comment]
Nevermind, it's php sending an extra \n in the response...
